<!doctype html>
<html>
<head>

  <meta name="viewport" content="initial-scale=1.0, maximum-scale=4.0, user-scalable=yes">

	<title>dat bostwiek gettin dat new website</title>

	<link rel="stylesheet" type="text/css" href="css/style.css">
  <link rel="stylesheet" type="text/css" href="css/wookmark.css">
  <link rel="stylesheet" type="text/css" href="css/lightbox.css">

  <!--<link href='https://fonts.googleapis.com/css?family=Pompiere|Fredericka+the+Great|Lakki+Reddy|Pacifico|Patrick+Hand|Vibur' rel='stylesheet' type='text/css'>-->

  <link href='https://fonts.googleapis.com/css?family=Lakki+Reddy' rel='stylesheet' type='text/css'>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="js/custom.js"></script>
  <!--<script src="js/fullscreenslides.js"></script>-->