<header>

			<a href="index.php" class="logo"><img src="images/logo.png" alt="bostwiek's baby face"></a>

      <nav>

        <!-- <a class="nav-btn">...</a> -->

        <div class="nav-item dropdown-container">
          <a class="nav-primary">Portfolio</a>
          <div class="dropdown">
            <a href="traditional.php" class="nav-dropdown">Traditional</a>
            <a href="digital.php" class="nav-dropdown">Digital</a>
            <a href="webdesign.php" class="nav-dropdown">Web Design</a>
          </div>
        </div>
        <div class="nav-item">
          <a href="about.php" class="nav-primary">About</a>
        </div>
        <div class="nav-item">
          <a href="contact.php" class="nav-primary">Contact</a>
        </div>

      </nav>

  </header>